label_list = ['ARTS',
              'ARTS & CULTURE',
              'BLACK VOICES',
              'BUSINESS',
              'COLLEGE',
              'COMEDY',
              'CRIME',
              'CULTURE & ARTS',
              'DIVORCE',
              'EDUCATION',
              'ENTERTAINMENT',
              'ENVIRONMENT',
              'FIFTY',
              'FOOD & DRINK',
              'GOOD NEWS',
              'GREEN',
              'HEALTHY LIVING',
              'HOME & LIVING',
              'IMPACT',
              'LATINO VOICES',
              'MEDIA',
              'MONEY',
              'PARENTING',
              'PARENTS',
              'POLITICS',
              'QUEER VOICES',
              'RELIGION',
              'SCIENCE',
              'SPORTS',
              'STYLE',
              'STYLE & BEAUTY',
              'TASTE',
              'TECH',
              'TRAVEL',
              'WEDDINGS',
              'WEIRD NEWS',
              'WELLNESS',
              'WOMEN',
              'WORLD NEWS',
              'WORLDPOST']